# IMPORT NUMPY

In [3]:
import numpy as np

# CREATE ARRAYS

1D ARRAYS

In [5]:
a = np.array([10,20,30,40])
print (a)

[10 20 30 40]


2D ARRAY

In [136]:
a = np.array([[1,2,3],
             [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


# CHECK ARRAY TYPE

shape

In [27]:
a.shape

(2, 3)

Number of dimension

In [21]:
a.ndim

2

Data type

In [23]:
a.dtype

dtype('int64')

Size

In [26]:
a.size

6

# Create special arrays

In [30]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

ones

In [31]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

identity matrix

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Full array

In [36]:
np.full((2,2),6)

array([[6, 6],
       [6, 6]])

# Range Functions

## ARANGE

In [40]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## EVEN NUMPERS

In [42]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## linspace()

In [43]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Random numbers

## Random decimal

In [50]:
np.random.rand(5)

array([0.76471687, 0.23262976, 0.23325911, 0.57820748, 0.20724413])

## Random.integar

In [47]:
np.random.randint(1,100,10)

array([57, 71,  2, 62, 87, 33, 46, 63, 85,  7], dtype=int32)

## Random Normal Disrtribution 

In [60]:
np.random.randn(5)

array([ 1.54431221,  0.18728317, -0.23612746,  0.82595275, -0.87933655])

# Reshape Array

In [80]:
a = np.arange(12)

a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Flatten Array

In [82]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# indexing

In [24]:
a = np.array([10,20,30,40])

a[2]

np.int64(30)

In [86]:
a[-1]

np.int64(40)

# Slicing

In [110]:
a[1:4]

array([20, 30, 40])

# MATHEMATICAL OPERATIONS

In [111]:
a = np.array([1,2,3])

a + 10

array([11, 12, 13])

In [112]:
a * 5

array([ 5, 10, 15])

In [114]:
a ** 2

array([1, 4, 9])

In [115]:
a / 2

array([0.5, 1. , 1.5])

# Array to Array operations

In [37]:
a = np.array([1,2,3])

b = np.array([4,5,6])

a+b

array([5, 7, 9])

In [117]:
a * b

array([ 4, 10, 18])

# Aggreagate functions 

In [119]:
np.sum(a)

np.int64(6)

In [120]:
np.sum(b)

np.int64(15)

In [122]:
np.mean(a)

np.float64(2.0)

In [123]:
np.mean(b)

np.float64(5.0)

In [124]:
np.max(a)

np.int64(3)

In [125]:
np.min(a)

np.int64(1)

## standard deviation

In [126]:
np.std(a)

np.float64(0.816496580927726)

## variance

In [128]:
np.var(a)

np.float64(0.6666666666666666)

# Sorting

In [129]:
np.sort(a)

array([1, 2, 3])

# Unique values

In [131]:
np.unique(a)

array([1, 2, 3])

# Transpose

In [137]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# Matrix multiplication

In [5]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])
A @ B
              

array([[19, 22],
       [43, 50]])

## OR

In [6]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

# BOOLEAN FILTERING

In [26]:
a = np.array([10,20,30,40,50])

a[a > 15]

array([20, 30, 40, 50])

# Copy array

In [11]:
b = a.copy()
print(b)

[10 20 30 40 50]


## Change Data type

In [20]:

a.astype(str)

array(['10', '20', '30', '40', '50'], dtype='<U21')

## Find maximum Index

In [28]:
np.argmax(a)

np.int64(4)

## Find Mininum Index

In [29]:
np.argmin(a)

np.int64(0)

## Concatenate Arrays

In [32]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

## Vertical Stack

In [38]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

## Horizontal Stack

In [39]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])